version: '3'
services:
  api1: &api
  hostname: api1
  container_name: api1
  depends_on:
    - mysql
  network_mode:
    - mvc
  environment:
    MYSQL_USER: pedro157
    MYSQL_PASS: Hinamizawa$_$
    MYSQL_DATABASE: go_test
  deploy:
    resources:
      limits:
        cpus: '0.9'
        memory: '1GB'
  api2:
    <<: *api
    hostname: api2
    container_name: api2

  nginx: 
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    ports:
      - "9999:9999"
    network_mode:
      - mvc
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1GB'
   
  mysql:
    image: mysql:latest
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Hinamizawa$_$
      MYSQL_USER: pedro157
      MYSQL_PASS: Hinamizawa$_$
      MYSQL_DATABASE: go_test
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "1500:1500"
    expose:
      - 1500
    network_mode:
      - mvc
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: '2GB'

networks:
  mvc: