version: '3.8'
services:
  mariadb:
    image: mariadb:latest
    hostname: mariadb
    healthcheck:
      test: "mariadb -h localhost -u root -pHinamizawa*_* -e \"use go_test;\""
      start_period: 10s
      interval: 5s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: Hinamizawa*_*
      MYSQL_DATABASE: go_test
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - mariadb_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.24GB'

  api1: &api
    hostname: api1
    build: ./
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      MYSQL_USER: pedro157
      MYSQL_PASS: Hinamizawa*_*
      MYSQL_DATABASE: go_test
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.24GB'
  api2:
    <<: *api
    hostname: api2
    environment:
      MYSQL_USER: pedro157
      MYSQL_PASS: Hinamizawa*_*
      MYSQL_DATABASE: go_test

  nginx: 
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.24GB'
    ports:
      - "80:9999"

volumes:
  mariadb_data:
